export enum AccountTabState {
  LOGIN = "LOGIN",
  REGISTER = "REGISTER",
  ACCOUNT_TYPE = "ACCOUNT_TYPE",
  PROFILE_DATA = "PROFILE_DATA",
  OTP_VERIFICATION = "OTP_VERIFICATION",
  COMPLETED = "COMPLETED",
}

export enum LoginTabState {
  LOGIN = "LOGIN",
  UNVERIFIED = "UNVERIFIED",
  OTP_VERIFICATION = "OTP_VERIFICATION",
  COMPLETED = "COMPLETED",
}

export enum ErrorCodes {
  EMAIL_NOT_VERIFIED = "EMAIL_NOT_VERIFIED",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
}
