export enum AccountTabState {
  LOGIN = "LOGIN",
  REGISTER = "REGISTER",
  ACCOUNT_TYPE = "ACCOUNT_TYPE",
  PROFILE_DATA = "PROFILE_DATA",
  OTP_VERIFICATION = "OTP_VERIFICATION",
  COMPLETED = "COMPLETED",
}
